import numpy
import pygame as pg
import numpy as np
from scipy.io import loadmat

pg.init()
WIDTH, HEIGHT = 1440, 770
WINDOW = pg.display.set_mode((WIDTH, HEIGHT))
pg.display.set_caption("Drawing digits")
TOP_LEFT_X, TOP_LEFT_Y = 125, 50
FPS = 120
RESOLUTION = 12
SQUARE_SIZE = 24 // RESOLUTION
weights = loadmat("weights.mat")
# USES ALT MODEL
W1 = weights["W1"]
W2 = weights["W2"]
W3 = weights["W3"]
B1 = weights["B1"]
B2 = weights["B2"]
B3 = weights["B3"]
fract = 1 / (RESOLUTION ** 2)


def softmax(x: np.ndarray) -> np.ndarray:
    # Subtract the max value from x for numerical stability
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)


def generate_matrix(drawing):
    drawing_np = np.array(drawing, dtype=np.int16)

    # Reshape the drawing into blocks of size RESOLUTION x RESOLUTION
    reshaped_drawing = drawing_np.reshape(28, RESOLUTION, 28, RESOLUTION)

    # Sum over each block (axis=(1, 3) sums over RESOLUTION dimensions)
    output = reshaped_drawing.sum(axis=(1, 3)) * fract

    return output


def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1 / (1 + np.exp(-x))


#test = numpy.fromiter([0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.1137,
     #                  0.2549,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0667,
     #                  0.6941,
     #                  0.8471,
     #                  0.4314,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0392,
     #                  0.6314,
     #                  1.0000,
     #                  1.0000,
     #                  0.3922,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0510,
     #                  0.3725,
     #                  0.8353,
     #                  0.9922,
     #                  0.8588,
     #                  0.2431,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.1647,
     #                  0.6863,
     #                  0.9333,
     #                  0.8941,
     #                  0.4510,
     #                  0.1216,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.2627,
     #                  0.8784,
     #                  0.9843,
     #                  0.7804,
     #                  0.4157,
     #                  0.2824,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.3333,
     #                  0.9843,
     #                  1.0000,
     #                  0.9412,
     #                  0.8039,
     #                  0.1608,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0275,
     #                  0.4745,
     #                  1.0000,
     #                  1.0000,
     #                  0.7294,
     #                  0.0471,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0235,
     #                  0.7294,
     #                  0.9922,
     #                  0.9843,
     #                  0.4706,
     #                  0.0510,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.6000,
     #                  0.9529,
     #                  0.9725,
     #                  0.9843,
     #                  0.7373,
     #                  0.1451,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.1529,
     #                  0.2157,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.4863,
     #                  0.8784,
     #                  0.9176,
     #                  0.3294,
     #                  0.8157,
     #                  0.8392,
     #                  0.4118,
     #                  0.0745,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0627,
     #                  0.6275,
     #                  0.8078,
     #                  0.1922,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.3647,
     #                  0.7804,
     #                  0.9608,
     #                  0.2549,
     #                  0.0627,
     #                  0.3569,
     #                  0.8902,
     #                  0.6941,
     #                  0.2235,
     #                  0.0275,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0510,
     #                  0.6392,
     #                  0.9098,
     #                  0.5451,
     #                  0.0745,
#                       0,
#                       0,
#                       0,
     #                  0.2510,
     #                  0.6588,
     #                  1.0000,
     #                  0.3647,
     #                  0.0314,
#                       0,
     #                  0.2000,
     #                  0.6510,
     #                  0.9608,
     #                  0.5725,
     #                  0.0510,
     #                  0.0039,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0196,
     #                  0.2784,
     #                  0.8863,
     #                  0.6980,
     #                  0.1216,
#                       0,
#                       0,
     #                  0.1451,
     #                  0.5176,
     #                  0.9765,
     #                  0.5255,
     #                  0.1137,
#                       0,
#                       0,
#                       0,
     #                  0.3922,
     #                  0.9373,
     #                  0.9882,
     #                  0.4275,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.2039,
     #                  0.7529,
     #                  0.9020,
     #                  0.3333,
#                       0,
     #                  0.0549,
     #                  0.3569,
     #                  0.9373,
     #                  0.7216,
     #                  0.2706,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.5765,
     #                  0.9804,
     #                  0.7843,
     #                  0.2196,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0039,
     #                  0.5176,
     #                  0.9412,
     #                  0.3843,
     #                  0.0353,
     #                  0.1843,
     #                  0.8863,
     #                  0.9176,
     #                  0.4902,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0196,
     #                  0.1529,
     #                  0.6824,
     #                  0.8431,
     #                  0.2431,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0196,
     #                  0.2863,
     #                  0.8392,
     #                  0.6627,
     #                  0.1608,
     #                  0.7843,
     #                  0.9922,
     #                  0.7412,
     #                  0.0314,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0667,
     #                  0.2118,
     #                  0.3608,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.1529,
     #                  0.8118,
     #                  0.7843,
     #                  0.7882,
     #                  0.9451,
     #                  0.8706,
     #                  0.2784,
     #                  0.0235,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0392,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0627,
     #                  0.5176,
     #                  0.9804,
     #                  0.9608,
     #                  0.9686,
     #                  0.6549,
     #                  0.1569,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.4314,
     #                  0.9412,
     #                  1.0000,
     #                  0.9490,
     #                  0.3490,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0039,
     #                  0.1569,
     #                  0.8000,
     #                  1.0000,
     #                  0.6549,
     #                  0.0941,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.1412,
     #                  0.7569,
     #                  0.8745,
     #                  0.5804,
     #                  0.0235,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.2510,
     #                  0.4431,
     #                  0.0941,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
     #                  0.0314,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#                       0,
#           0], np.double)
# vecin = test.flatten(order="F").reshape(-1, 1)
# tmp = softmax(W4 @ sigmoid(W3 @ sigmoid(W2 @ sigmoid(W1 @ vecin + B1) + B2) + B3) #+ B4)
# for i in range(10):
#    print(f"Probability of {i}: {tmp[i, 0] * 100} %")


def main():
    draw_mode = False
    eraser_mode = False
    passive_mode = True
    run = True
    clock = pg.time.Clock()
    drawing = [[(i + j) % 2 for i in range(28 * RESOLUTION)] for j in range(28 * RESOLUTION)]
    input_NN = generate_matrix(drawing)
    BRUSH_SIZE = RESOLUTION // 2
    while run:
        clock.tick(FPS)
        for event in pg.event.get():
            if event.type == pg.QUIT:
                run = False

            if event.type == pg.KEYDOWN:
                if event.key == pg.K_p:
                    # Enter passive mode
                    draw_mode = False
                    eraser_mode = False
                    passive_mode = True
                if event.key == pg.K_d:
                    # Enter draw mode
                    draw_mode = True
                    eraser_mode = False
                    passive_mode = False
                if event.key == pg.K_e:
                    # Enter eraser mode
                    draw_mode = False
                    eraser_mode = True
                    passive_mode = False
                if event.key == pg.K_c:
                    # clear board + enter passive mode
                    draw_mode = False
                    eraser_mode = False
                    passive_mode = True
                    drawing = [[0 for _ in range(28 * RESOLUTION)] for _ in range(28 * RESOLUTION)]
                    input_NN = np.zeros((28, 28), np.double)
                if event.key == pg.K_m:
                    vecin = input_NN.flatten(order="F").reshape(-1, 1)
                    tmp = softmax(W3 @ sigmoid(W2 @ sigmoid(W1 @ vecin + B1) + B2) + B3)
                    for i in range(10):
                        print(f"Probability of {i}: {tmp[i, 0] * 100} %")

                elif event.unicode.isdigit():  # Only allow numeric input
                    BRUSH_SIZE = int(event.unicode)
        draw(WINDOW, drawing, input_NN)
        pg.display.update()
        mouse_pos = pg.mouse.get_pos()

        if not passive_mode and (TOP_LEFT_X < mouse_pos[0] < TOP_LEFT_X + len(drawing[0]) * SQUARE_SIZE) and (
                TOP_LEFT_Y < mouse_pos[1] < TOP_LEFT_Y + len(drawing) * SQUARE_SIZE):
            translated_mouse_x, translated_mouse_y = mouse_pos[0] - TOP_LEFT_X, mouse_pos[1] - TOP_LEFT_Y
            j, i = translated_mouse_x // SQUARE_SIZE, translated_mouse_y // SQUARE_SIZE
            if i < len(drawing) and j < len(drawing[0]):
                if eraser_mode and drawing[i][j] == 1:
                    drawing[i][j] = 0
                    input_NN[i // RESOLUTION, j // RESOLUTION] -= fract
                if draw_mode and drawing[i][j] == 0:
                    drawing[i][j] = 1
                    input_NN[i // RESOLUTION, j // RESOLUTION] += fract
            for n in range(max(i - BRUSH_SIZE, 0), min(i + BRUSH_SIZE + 1, len(drawing))):
                for m in range(max(j - BRUSH_SIZE, 0), min(j + BRUSH_SIZE + 1, len(drawing[0]))):
                    if n != i or m != j:
                        if eraser_mode and drawing[n][m] == 1:
                            drawing[n][m] = 0
                            input_NN[n // RESOLUTION, m // RESOLUTION] -= fract
                        if draw_mode and drawing[n][m] == 0:
                            drawing[n][m] = 1
                            input_NN[n // RESOLUTION, m // RESOLUTION] += fract
    pg.quit()


def draw(window: pg.surface, drawing, input_NN):
    window.fill((0, 0, 55))
    for row in range(len(drawing)):
        for column in range(len(drawing[row])):
            if drawing[row][column] == 1:
                pg.draw.rect(window, (255, 255, 255), (
                    TOP_LEFT_X + column * SQUARE_SIZE, TOP_LEFT_Y + row * SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE))

    # We draw input image 112x112
    size = int(112 / 28)
    factor = 255
    for i in range(28):
        for j in range(28):
            val = round(input_NN[i, j] * factor)
            pg.draw.rect(window, (val, val, val),
                         (5 + j * size, 5 + i * size, size, size))

    # DRAW LINES TO IMPROVE CLARITY BOARD
    # for row in range(len(drawing)+1):
    #    pg.draw.line(window, (0, 0, 0), (TOP_LEFT_X+row*SQUARE_SIZE, TOP_LEFT_Y), (TOP_LEFT_X+row*SQUARE_SIZE, TOP_LEFT_Y+len(drawing)*SQUARE_SIZE))

    # for column in range(len(drawing[0])+1):
    #    pg.draw.line(window, (0, 0, 0), (TOP_LEFT_X, TOP_LEFT_Y+column*SQUARE_SIZE), (TOP_LEFT_X+len(drawing[0])*SQUARE_SIZE, TOP_LEFT_Y+column*SQUARE_SIZE))
    pg.draw.line(window, (0, 0, 0), (TOP_LEFT_X + 0 * SQUARE_SIZE, TOP_LEFT_Y),
                 (TOP_LEFT_X + 0 * SQUARE_SIZE, TOP_LEFT_Y + len(drawing) * SQUARE_SIZE))
    pg.draw.line(window, (0, 0, 0), (TOP_LEFT_X + len(drawing) * SQUARE_SIZE, TOP_LEFT_Y),
                 (TOP_LEFT_X + len(drawing) * SQUARE_SIZE, TOP_LEFT_Y + len(drawing) * SQUARE_SIZE))
    pg.draw.line(window, (0, 0, 0), (TOP_LEFT_X, TOP_LEFT_Y + 0 * SQUARE_SIZE),
                 (TOP_LEFT_X + len(drawing[0]) * SQUARE_SIZE, TOP_LEFT_Y + 0 * SQUARE_SIZE))
    pg.draw.line(window, (0, 0, 0), (TOP_LEFT_X, TOP_LEFT_Y + len(drawing[0]) * SQUARE_SIZE),
                 (TOP_LEFT_X + len(drawing[0]) * SQUARE_SIZE, TOP_LEFT_Y + len(drawing[0]) * SQUARE_SIZE))

    font = pg.font.Font(None, 18)
    text_surface = font.render(" Choose between (d)raw mode, (e)raser mode, (p)assive mode or (c)learing the board",
                               True, (255, 255, 255))  # White text
    text_rect = text_surface.get_rect()

    # Position the text under the board
    text_rect.center = (TOP_LEFT_X + len(drawing[0]) * SQUARE_SIZE // 2,
                        TOP_LEFT_Y + len(drawing) * SQUARE_SIZE + 20)

    # Draw the text on the window
    window.blit(text_surface, text_rect)

    font = pg.font.Font(None, 30)

    vecin = input_NN.flatten(order="F").reshape(-1, 1)
    tmp = softmax(W3 @ sigmoid(W2 @ sigmoid(W1 @ vecin + B1) + B2) + B3)
    tmp = tmp.flatten()
    digits_sorted = tmp.argsort()[::-1]
    tmp = np.round(tmp, 2)
    for i in range(10):
        text_surface = font.render(f"Probability that this is {digits_sorted[i]}: {100*tmp[digits_sorted[i]]} %",
                                   True, (255, 255, 255))  # White text
        text_rect = text_surface.get_rect()

        # Position the text under the board
        text_rect.topleft = (TOP_LEFT_X + len(drawing[0]) * SQUARE_SIZE +20,
                            TOP_LEFT_Y + i*44)

        window.blit(text_surface, text_rect)


if __name__ == "__main__":
    main()
